# Dependencies
kramdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Shengrong
tagline:          ·Hello Universe·
url:              http://syin.us
paginate:         20
baseurl:          /
author:
  name:           'Shengrong Yin'
  url:            https://www2.cs.uh.edu/~syin
  email:          syin@uh.edu

# Custom vars
version:          1.0.0
github:
  repo:           github.com/yinshengrong/yinshengrong.github.io

# Page lists
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Twonet: '/twonet/'
  Paper: '/paper/'
