# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Shengrong Yin
tagline:          ·Hello World
url:              http://syin.us
paginate:         1
baseurl:          /
author:
  name:           Shengrong Yin
  url:            https://twitter.com/mdo
  email:          syin@uh.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# Page lists
pages_list:       {'About':'/about', 'Archive':'/archive', 'Twonet':'/twonet'}
